-- DDL & dummy Date insert
-- 테이블 및 시퀀스 삭제
DROP TABLE PERSON;
DROP TABLE JOB;
DROP SEQUENCE PERSON_SEQ;

-- 테이블 및 시퀀스 생성
CREATE TABLE JOB(
    jNO   NUMBER(2)    PRIMARY KEY,
    jNAME VARCHAR2(30) NOT NULL UNIQUE
);
CREATE SEQUENCE PERSON_SEQ
    MAXVALUE 99999 NOCACHE NOCYCLE;
CREATE TABLE PERSON(
    pNO NUMBER(5)     PRIMARY KEY,
    pNAME VARCHAR(30) NOT NULL,
    jNO NUMBER(2)     REFERENCES JOB(jNO),
    KOR NUMBER(3)     CHECK(KOR >= 0 AND KOR <= 100),
    ENG NUMBER(3)     CHECK(ENG >= 0 AND ENG <= 100),
    MAT NUMBER(3)     CHECK(MAT >= 0 AND MAT <= 100)
);
-- DUMMY DATA
-- JOB(10, 배우) (20, 가수) (30, 엠씨)
INSERT INTO JOB VALUES(10, '배우');
INSERT INTO JOB VALUES(20, '가수');
INSERT INTO JOB VALUES(30, '엠씨');
SELECT * FROM JOB;
-- PERSON (3명) 학번, 학생이름, 직업번호, 국어점수, 영어점수, 수학점수
INSERT INTO PERSON VALUES(PERSON_SEQ.NEXTVAL, '정우성', 10, 90, 80, 81);
INSERT INTO PERSON VALUES(PERSON_SEQ.NEXTVAL, '박세영', 10, 80, 90, 80);
INSERT INTO PERSON VALUES(PERSON_SEQ.NEXTVAL, '배수지', 20, 20, 90, 90);
SELECT * FROM PERSON;
COMMIT;