-- DDL & dummy Date insert
-- 테이블 및 시퀀스 삭제
DROP TABLE PERSON;
DROP TABLE JOB;
DROP SEQUENCE PERSON_SEQ;
DROP SEQUENCE JOB_SEQ;
-- 테이블 및 시퀀스 생성
CREATE TABLE JOB(
    jNO NUMBER(2) PRIMARY KEY,
    jNAME VARCHAR2(30) NOT NULL
);
CREATE TABLE PERSON(
    pNO NUMBER(5) PRIMARY KEY,
    pNAME VARCHAR(30) NOT NULL,
    
);
-- DUMMY DATA
-- JOB(10, 배우) (20, 가수) (30, 엠씨)
-- PERSON (3명)
